alert:
  auto_save_ng_frames: true
  log_missing_frames: true
  missing_part_sound: true
  ng_save_dir: logs/ng_frames
camera1:
  buffer_size: 1
  digital_zoom: 1.0
  enabled: true
  fps: 15
  height: 2048
  label: Left View
  reconnect_delay: 3
  rtsp_url: rtsp://admin:admin123@192.168.1.64/Streaming/Channels/101
  width: 3072
camera2:
  buffer_size: 1
  digital_zoom: 1.0
  enabled: true
  fps: 15
  height: 2048
  label: Right View
  reconnect_delay: 3
  rtsp_url: rtsp://admin:admin123@192.168.1.65/Streaming/Channels/101
  width: 3072
checkpoints:
  CL-01:
    h: 0.06
    name: Resilience bkt.
    w: 0.06
    x: 0.4451
    y: 0.2408
  CL-04:
    h: 0.06
    name: B/S Bumper support bkt.
    w: 0.06
    x: 0.1321
    y: 0.2428
  CL-05:
    h: 0.06
    name: Bumper support bkt
    w: 0.06
    x: 0.1122
    y: 0.8487
  CL-08:
    h: 0.08
    name: B/S Trunnion bkt mtg on frame
    w: 0.06
    x: 0.7770
    y: 0.8049
  CL-12:
    h: 0.06
    name: B/S Eng Mtg Bkt
    w: 0.06
    x: 0.3148
    y: 0.8390
  CL-15:
    h: 0.06
    name: APU Fitment with bkt
    w: 0.06
    x: 0.5198
    y: 0.8364
  CL-18:
    h: 0.08
    name: B/S ARB Rear mtg BKT
    w: 0.06
    x: 0.9390
    y: 0.8099
  CL-19:
    h: 0.06
    name: Articulation Stopper
    w: 0.06
    x: 0.8109
    y: 0.2598
conveyor_direction: left_to_right
database:
  database: kitting_zone_4
  host: 192.168.11.199
  password: postgres
  port: 5432
  table: kitting_zone_4
  user: postgres
  vc_column: VC_no
  vin_column: VIN_no
detection:
  confidence_threshold: 0.45
  frame_skip: 3
  model_path: assets/best.pt
  nms_threshold: 0.4
  roi_bottom_pct: 1.0
  roi_left_pct: 0.0
  roi_right_pct: 1.0
  roi_top_pct: 0.0
  use_gpu: false
line_id: LINE-03
reference_image: new_qa.png
serial:
  baudrate: 9600
  bytesize: 8
  enabled: true
  flow_control: none
  parity: N
  port: COM4
  stopbits: 1
station_id: 01_VIN_Scan
theme: dark
